version: "3.3"
services:
        web:
                image: egg-server_web
                build: .
                links:
                        - "mongodb:mongodb"
                ports:
                        - "7001:7001"
                depends_on: 
                        - mongodb
        mongodb:
                image: mongo
                ports:
                        - "27017:27017"
                volumes: 
                        - "./mongodb/data:/data/db"
        frontend:
                image: egg-client
                ports:
                        - "3000:3000"
